In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv("D:\Data sets\Salaries.csv")

In [4]:
data

Unnamed: 0      rank discipline  yrs_since_phd  yrs_service   sex  salary
0             1      Prof          B             19           18  Male  139750
1             2      Prof          B             20           16  Male  173200
2             3  AsstProf          B              4            3  Male   79750
3             4      Prof          B             45           39  Male  115000
4             5      Prof          B             40           41  Male  141500
..          ...       ...        ...            ...          ...   ...     ...
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns]

In [5]:
data = data.iloc[:,1:]

In [6]:
data.corr()

yrs_since_phd  yrs_service    salary
yrs_since_phd       1.000000     0.909649  0.419231
yrs_service         0.909649     1.000000  0.334745
salary              0.419231     0.334745  1.000000

In [7]:
le = LabelEncoder()

In [8]:
cat_col = ['rank', 'discipline', 'sex']
for col in cat_col:
    data[col] = le.fit_transform(data[col])

In [9]:
sc = StandardScaler()

In [10]:
import numpy as np

In [11]:
scaled_data = sc.fit_transform(data[['salary']])

In [12]:
scaled_data

array([[ 8.60918841e-01],
       [ 1.96667226e+00],
       [-1.12249537e+00],
       [ 4.27604786e-02],
       [ 9.18768422e-01],
       [-5.52263785e-01],
       [ 2.02617469e+00],
       [ 1.12586992e+00],
       [ 1.83252319e-01],
       [ 5.05557128e-01],
       [ 2.01433616e-01],
       [-1.12084253e+00],
       [-1.19026202e+00],
       [-1.18034495e+00],
       [-2.94419937e-01],
       [ 1.13832821e-01],
       [-4.20036171e-01],
       [-3.39046757e-01],
       [ 3.65065288e-01],
       [ 7.70012356e-01],
       [-7.98041863e-01],
       [-3.67806263e-01],
       [-6.54607958e-01],
       [-2.11054590e-02],
       [-1.28513534e+00],
       [-2.45032924e-01],
       [ 7.00097005e-01],
       [-1.03558877e+00],
       [-1.21340186e+00],
       [ 1.49302879e-01],
       [ 6.13355690e-01],
       [-1.11700792e+00],
       [ 1.17336853e-01],
       [-1.10679334e+00],
       [-1.10679334e+00],
       [-1.21340186e+00],
       [ 1.38982930e+00],
       [-9.03559499e-01],
       [ 3.7

In [13]:
x = data.iloc[:,0:5]
y = scaled_data

In [14]:
x

rank  discipline  yrs_since_phd  yrs_service  sex
0       2           1             19           18    1
1       2           1             20           16    1
2       1           1              4            3    1
3       2           1             45           39    1
4       2           1             40           41    1
..    ...         ...            ...          ...  ...
392     2           0             33           30    1
393     2           0             31           19    1
394     2           0             42           25    1
395     2           0             25           15    1
396     1           0              8            4    1

[397 rows x 5 columns]

In [15]:
y

array([[ 8.60918841e-01],
       [ 1.96667226e+00],
       [-1.12249537e+00],
       [ 4.27604786e-02],
       [ 9.18768422e-01],
       [-5.52263785e-01],
       [ 2.02617469e+00],
       [ 1.12586992e+00],
       [ 1.83252319e-01],
       [ 5.05557128e-01],
       [ 2.01433616e-01],
       [-1.12084253e+00],
       [-1.19026202e+00],
       [-1.18034495e+00],
       [-2.94419937e-01],
       [ 1.13832821e-01],
       [-4.20036171e-01],
       [-3.39046757e-01],
       [ 3.65065288e-01],
       [ 7.70012356e-01],
       [-7.98041863e-01],
       [-3.67806263e-01],
       [-6.54607958e-01],
       [-2.11054590e-02],
       [-1.28513534e+00],
       [-2.45032924e-01],
       [ 7.00097005e-01],
       [-1.03558877e+00],
       [-1.21340186e+00],
       [ 1.49302879e-01],
       [ 6.13355690e-01],
       [-1.11700792e+00],
       [ 1.17336853e-01],
       [-1.10679334e+00],
       [-1.10679334e+00],
       [-1.21340186e+00],
       [ 1.38982930e+00],
       [-9.03559499e-01],
       [ 3.7

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=111)

In [17]:
model = DecisionTreeRegressor()

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lr = LinearRegression()

In [20]:
lr.fit(x_train,y_train)

LinearRegression()

In [21]:
lr.score(x_train,y_train)

0.35584632148434536

In [22]:
pr = lr.predict(x_test)

In [25]:
print(r2_score(y_test,pr))

0.42255285038660384


In [26]:
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [27]:
model.score(x_test,y_test)

0.06669580446959011

In [28]:
model.score(x_train, y_train)

0.9212929480349994

In [29]:
pred = model.predict(x_test)
pred

array([-1.3538937 , -1.1968734 ,  2.19145921, -1.64644729, -0.12963127,
        0.90673571, -0.78557941,  0.09069299,  2.01691876, -1.11892523,
       -0.32912969,  0.18325232, -0.66200169,  1.94369772, -1.03558877,
       -0.36780626, -0.41309422,  0.75877301, -0.07789722, -1.41941248,
        0.82855613, -0.41309422, -0.33246843, -0.31164258,  0.77553286,
       -0.7687865 ,  1.24437892, -0.29441994, -0.33904676, -0.60750187,
       -1.1743286 , -0.67907007, -0.98200353,  0.73695545, -1.34562947,
        0.27746449,  1.08581597, -1.17498973, -0.03340263,  1.8157675 ,
       -0.2051663 , -0.94894663,  0.77553286,  0.56056382, -0.35041833,
       -0.70597839, -1.4712457 , -0.68085514,  1.21561942, -1.42166035,
       -0.67067361, -1.8480944 , -0.59715506,  0.09069299,  0.63199978,
       -1.64644729,  1.8157675 , -0.08391358,  0.42691475, -0.84977592,
        2.68070138, -0.32879912,  0.64495809, -0.82828893, -0.68085514,
       -0.33904676, -0.37921089,  1.8157675 ,  0.41630349,  1.12

In [24]:
from sklearn.metrics import r2_score, mean_squared_error

In [ ]:
print(r2_score(pred, y_test))